# -*- coding: utf-8 -*-
"""Global_Cancer_Patients_2015_2024.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gBOg3jtMziBiLu3opmsLfHg_oS3HPhu6
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

import warnings
warnings.filterwarnings("ignore")

df = pd.read_csv("/content/global_cancer_patients_2015_2024.csv")

df.head()



df.info()



df.describe()

#Gives a statistical summary of all numerical columns — like Age, Survival_Years, Treatment_Cost_USD, etc.
#Includes: mean, standard deviation, min, max, and quartiles.



# Gender-wise count

df["Gender"].value_counts()

#Shows how many patients are Male, Female, or Other.



# Top 10 countries by patient count

df["Country_Region"].value_counts().head(10)

#Displays the top 10 countries with the highest number of cancer patients.



# Top 10 cancer types

df["Cancer_Type"].value_counts().head(10)

#Shows the most common cancer types among patients, like Breast, Colon, Lung, etc.





# Age Distribution Plot

plt.figure(figsize=(10, 6))
sns.histplot(df["Age"], bins=30, kde=True, color="skyblue")
plt.title("Age Distribution of Cancer Patients")
plt.xlabel("Age")
plt.ylabel("Frequency")
plt.show()

#Visualizes the spread of ages among cancer patients — helps you see if most patients are young, middle-aged, or elderly.





# Gender Distribution Plot

plt.figure(figsize=(10, 6))
sns.countplot(data=df, x="Gender", palette="Set2")
plt.title("Gender Wise Patients Count")
plt.xlabel("Gender")
plt.ylabel("Count")
plt.show()

#Visualizes the top 10 countries where most patients in the dataset are from.





# Top 10 Countries by Count

top_countries = df["Country_Region"].value_counts().head(10)
plt.figure(figsize=(8, 6))
sns.barplot(x=top_countries.index, y=top_countries.values, palette="viridis")
plt.title("Top 10 Countries with Most Cancer Patients")
plt.xlabel("Country")
plt.ylabel("Count")
plt.xticks(rotation=45)
plt.show()

#Visualizes the top 10 countries where most patients in the dataset are from.





# Top 10 Cancer Types

top_cancer = df["Cancer_Type"].value_counts().head(10)
plt.figure(figsize=(8, 6))
sns.barplot(x=top_cancer.index, y=top_cancer.values, palette="magma")
plt.title("Top 10 Cancer Types")
plt.xlabel("Cancer Type")
plt.ylabel("Count")
plt.xticks(rotation=45)
plt.show()

#Bar chart showing which cancer types are most common.





# Stage-wise distribution

stage_counts = df["Cancer_Stage"].value_counts()

yearly_count = df["Year"].value_counts().sort_index()



# Stage Distribution

plt.figure(figsize=(8, 6))
sns.barplot(x=stage_counts.index, y=stage_counts.values, palette="viridis")
plt.title("Distribution of Cancer Stages")
plt.xlabel("Stage")
plt.ylabel("Count")
plt.show()

#Shows how many patients were diagnosed at each cancer stage.





#Year-wise Trend

plt.figure(figsize=(8, 6))
sns.lineplot(x=yearly_count.index, y=yearly_count.values, marker="o", color="teal")
plt.title("Year-wise Trend of Cancer Patients (2016–2024)")
plt.xlabel("Year")
plt.ylabel("Number of Patients")
plt.tight_layout
plt.show()

#Displays the yearly trend of reported cancer cases from 2016 to 2024.



import pandas as pd

# Load the dataset
df = pd.read_csv("global_cancer_patients_2015_2024.csv")

# Total number of rows (patients)
total_patients = df.shape[0]

print("🧑‍⚕️ Total Patients:", total_patients)





















